### ISSUE TITLE
How to config bcrypt ?

### ISSUE THREAD

**Issue by yixingjia** [emqx/emqx-auth-redis#74]
Hi team, I try to use bcrypt method for password hash.  But it always report incorrect password.

Here is my configuration for the emq_auth_redis

The password plain text is "password"

auth.redis.auth_cmd = HMGET mqtt_user:%u password
auth.redis.password_hash = bcrypt

127.0.0.1:6379> HGETALL mqtt_user:usera
1) "password"
2) "$2a$06$eHX8EKlD8G.A/4/hqnN8DuHbBFx/5.H5kCzXnHI93vnJXi.Uzo8Kq"
3) "is_superuser"
4) "1"

I Also try the follow configurations but still not works.

auth.redis.auth_cmd = HMGET mqtt_user:%u password salt
auth.redis.password_hash = salt,bcrypt

127.0.0.1:6379> HGETALL mqtt_user:usera
1) "password"
2) "$2a$06$eHX8EKlD8G.A/4/hqnN8DuHbBFx/5.H5kCzXnHI93vnJXi.Uzo8Kq"
3) "salt"
4) "$2a$06$eHX8EKlD8G.A/4/hqnN8Du"
5) "is_superuser"
6) "1"

Any suggestion on this?

I use python to valid the above hash and it is correct. So I think it should not be hash issue.

>>> bcrypt.hashpw("password","$2a$06$eHX8EKlD8G.A/4/hqnN8DuHbBFx/5.H5kCzXnHI93vnJXi.Uzo8K")
>>> '$2a$06$eHX8EKlD8G.A/4/hqnN8DuHbBFx/5.H5kCzXnHI93vnJXi.Uzo8Kq'

**Comment by kotky** [comment]
Hi, I can tell you what worked for me:
HMGET mqtt_user:%u password salt
12 passes since there is no way to change the default
the same password and hash save as you

**Comment by ngjaying** [comment]
@yixingjia 
1. auth.redis.password_hash = bcrypt is not supported. For bcrypt, you'll need to use auth.redis.password_hash = salt,bcrypt

2. I try the below configuration with the exact same redis data as you.  It works fine for me.
auth.redis.auth_cmd = HMGET mqtt_user:%u password salt
auth.redis.password_hash = salt,bcrypt
What happens when you use this configuration? Could you provide the erlang log?  Also have you reloaded the plugin once you changed the configuration? If you used dashboard, you'll need to firstly stop the plugin and then start again to let the new configuration take effect.

**Comment by yixingjia** [comment]
> @yixingjia
> 
>     1. auth.redis.password_hash = bcrypt is not supported. For bcrypt, you'll need to use auth.redis.password_hash = salt,bcrypt
> 
>     2. I try the below configuration with the exact same redis data as you.  It works fine for me.
>        auth.redis.auth_cmd = HMGET mqtt_user:%u password salt
>        auth.redis.password_hash = salt,bcrypt
>        What happens when you use this configuration? Could you provide the erlang log?  Also have you reloaded the plugin once you changed the configuration? If you used dashboard, you'll need to firstly stop the plugin and then start again to let the new configuration take effect.

Thanks it turn out the the bcrypt algorithm used by Erlang is different with others. I use the erlang version of bcrypt to get the password hash and it works.
We should really put this note in the configuration in case someone else try it with some online bcypte hash generator to get the hash and test.

**Comment by ngjaying** [comment]
@yixingjia I think bcrypt algorithm is independent of programming language. It makes no sense that the hash is different across language. 
I try your hash $2a$06$eHX8EKlD8G.A/4/hqnN8DuHbBFx/5.H5kCzXnHI93vnJXi.Uzo8Kq, it works just fine with Erlang. Here is the result I run with erlang-bcrypt:
1> bcrypt:hashpw("password", "$2a$06$eHX8EKlD8G.A/4/hqnN8Du").
{ok,"$2a$06$eHX8EKlD8G.A/4/hqnN8DuHbBFx/5.H5kCzXnHI93vnJXi.Uzo8Kq"}

See, the hash is exactly the same as yours that created by other hash generators. Could you try it? If you have other fail cases, please paste the hash string so that we can dig into. **Notice that, the hash started with $2b, $2y are not supported yet,**

**Comment by turtleDeng** [comment]
Thank you for your participation, we will close this issue.
