### ISSUE TITLE
bcrypt missing number of passes

### ISSUE THREAD

**Issue by kotky** [emqx/emqx-auth-redis#75]
Hi, I noticed that there is no way to configure number of passes when you use bcrypt hashing, from checking the code I noticed that default is 12, but it would be good to be able to adjust this from security perspective.

**Comment by ngjaying** [comment]
Duplicate to https://github.com/emqx/emqx-passwd/issues/1

**Comment by ngjaying** [comment]
Hi Josip,
The "number of passes" is contained on the salt. For example, salt "$2a$06$eHX8EKlD8G.A/4/hqnN8Du", the second $06 means the "number of passes" is 6.
Emqx does not generate the salt for you. It is created by the user so that the user can configure the preferred "number of passes". To provide the salt when using emqx-auth-redis, please set the salt for your mqtt users in Redis. Emqx will just read the salt info from redis.
```
HMSET mqtt_user:<username> password "hashedPassword" salt "salt"
```

**Comment by turtleDeng** [comment]
Thank you for your participation, we will close this issue.
